---
- name: playbook test
  hosts: all
  tasks:
          - name: ping test
            ping: 
          - name: command test
            command: /usr/bin/python --version
          - name: debug msg
            debug:
                    msg: "debug message"

